services:
  postgres:
    image: postgres:16-alpine
    container_name: library_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: VKIDIPLOM2026
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d library_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  library_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library_api
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=library_db;Username=postgres;Password=VKIDIPLOM2026
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy 
    networks:
      - library_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  library_network:
    driver: bridge
